import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import * as Clipboard from 'expo-clipboard';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAuth } from '@/contexts/AuthContext';
import { findSuitHolder, getMySuits, SUITS, SuitHolder, SuitKey, SuitState, SuitTask, getSuitAdmin, setSuitAssignment, setSuitInPlay, stampSuitCompletion } from '@/lib/suitsService';

const GOLD = '#D4A853'; const CREAM = '#EDE0C4';
export default function SuitsScreen() {
  const { user, jokerId } = useAuth(); const inset = useSafeAreaInsets();
  const [state, setState] = useState<SuitState | null>(null); const [holders, setHolders] = useState<SuitHolder[]>([]);
  const [lookup, setLookup] = useState(''); const [found, setFound] = useState<SuitHolder | null>(null); const [note, setNote] = useState('');
  const isJester = jokerId === '00-00';
  const load = async () => { try { if (isJester) { const r = await getSuitAdmin(); setHolders(r.holders); setState({ pips: [], streaks: {}, inPlay: r.inPlay, completed: {} }); } else setState((await getMySuits()).state); } catch (e: any) { setNote(e.message); } };
  useEffect(() => { if (user) void load(); }, [user?.uid, isJester]);
  if (!state) return <View style={s.center}><ActivityIndicator color={GOLD} /></View>;
  const mutate = async (work: () => Promise<void>) => { try { await work(); await load(); } catch (e: any) { setNote(e.message); } };
  return <View style={s.root}>
    <Image source={require('../../assets/images/wood_bg.png')} style={StyleSheet.absoluteFill} />
    <View style={[s.nav, { paddingTop: inset.top + 8 }]}><TouchableOpacity onPress={() => router.back()}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.navTitle}>SUITS</Text></View>
    <ScrollView contentContainerStyle={s.content}>
      <Text style={s.copy}>Pips are assigned by Jester 00-00. Opening this table never counts.</Text>
      {note ? <Text style={s.note}>{note}</Text> : null}
      <View style={s.cards}>{SUITS.map(suit => { const held = state.pips.includes(suit.key); const active = state.inPlay[suit.key]; return <TouchableOpacity disabled={!held || !active?.active} key={suit.key} onPress={() => { if (active?.destination === 'social') { const text = `#JestersHand ${jokerId ?? ''}`; void Clipboard.setStringAsync(text).then(() => setNote(`Copied: ${text}`)).catch(() => setNote(`Copy this: ${text}`)); } else if (active?.destination && active.destination !== 'discovery') router.push(`/(tabs)/${active.destination}` as any); }} style={[s.card, held && s.held]}>
        <Text style={s.pip}>{held ? suit.pip : '·'}</Text><Text style={s.suitName}>{suit.name}</Text>
        {held ? <Text style={s.meta}>Streak {state.streaks[suit.key] ?? 0}</Text> : null}
        {held && active?.active ? <><Text style={s.play}>{active.title}</Text>{active.instruction ? <Text style={s.meta}>{active.instruction}</Text> : null}</> : null}
        {held && state.completed[suit.key] ? <Text style={s.stamped}>Stamped</Text> : null}
      </TouchableOpacity>; })}</View>
      {!isJester && <><Text style={s.section}>OTHER JOKER</Text><View style={s.lookup}><TextInput value={lookup} onChangeText={setLookup} placeholder="Joker ID" placeholderTextColor="#8e8067" style={s.input} /><TouchableOpacity style={s.button} onPress={() => mutate(async () => setFound((await findSuitHolder(lookup.trim())).holder))}><Text style={s.buttonText}>LOOK</Text></TouchableOpacity></View>{found ? <Text style={s.result}>{found.jokerId}: {found.pips.map(p => SUITS.find(s => s.key === p)?.pip).join(' ') || 'no pips assigned'}</Text> : null}<Text style={s.footer}>3 / 6 / 9 notes arrive as your suit story grows. Share eligible work with #JestersHand + your Joker ID.</Text></>}
      {isJester && <Admin holders={holders} inPlay={state.inPlay} mutate={mutate} />}
    </ScrollView>
  </View>;
}
function Admin({ holders, inPlay, mutate }: { holders: SuitHolder[]; inPlay: Partial<Record<SuitKey, SuitTask>>; mutate: (fn: () => Promise<void>) => void }) {
  const [lookup, setLookup] = useState(''); const [member, setMember] = useState<SuitHolder | null>(null); const [drafts, setDrafts] = useState<Partial<Record<SuitKey, SuitTask>>>({});
  const task = (pip: SuitKey): SuitTask => drafts[pip] ?? inPlay[pip] ?? { active: false, title: '', destination: 'table' };
  return <View><Text style={s.section}>JESTER'S TABLE</Text><View style={s.lookup}><TextInput value={lookup} onChangeText={setLookup} placeholder="Find Joker ID" placeholderTextColor="#8e8067" style={s.input}/><TouchableOpacity style={s.button} onPress={() => mutate(async () => setMember((await findSuitHolder(lookup.trim())).holder))}><Text style={s.buttonText}>FIND</Text></TouchableOpacity></View>{member ? <Text style={s.result}>Selected: {member.jokerId}</Text> : null}
    {SUITS.map(x => { const d=task(x.key); return <View key={x.key} style={s.editor}><Text style={s.adminPip}>{x.pip} {x.name}</Text><TextInput value={d.title} onChangeText={v=>setDrafts(a=>({...a,[x.key]:{...d,title:v}}))} placeholder="Task title" placeholderTextColor="#8e8067" style={s.input}/><TextInput value={d.instruction ?? ''} onChangeText={v=>setDrafts(a=>({...a,[x.key]:{...d,instruction:v}}))} placeholder="Optional instruction" placeholderTextColor="#8e8067" style={s.input}/><View style={s.dest}>{(['table','jesters-deal','uniform','recruit','target-ticket','chamber','social','discovery'] as const).map(destination=><TouchableOpacity key={destination} style={s.small} onPress={()=>setDrafts(a=>({...a,[x.key]:{...d,destination}}))}><Text style={s.buttonText}>{destination}</Text></TouchableOpacity>)}</View><View style={s.dest}><TouchableOpacity style={s.small} onPress={()=>mutate(()=>setSuitInPlay(x.key,{...d,active:false}))}><Text style={s.buttonText}>SAVE</Text></TouchableOpacity><TouchableOpacity style={s.small} onPress={()=>mutate(()=>setSuitInPlay(x.key,{...d,active:true}))}><Text style={s.buttonText}>ACTIVATE</Text></TouchableOpacity><TouchableOpacity style={s.small} onPress={()=>mutate(()=>setSuitInPlay(x.key,{...d,active:false}))}><Text style={s.buttonText}>DEACTIVATE</Text></TouchableOpacity><TouchableOpacity style={s.small} disabled={!member} onPress={() => mutate(() => setSuitAssignment(member!.uid, x.key, true))}><Text style={s.buttonText}>ASSIGN</Text></TouchableOpacity><TouchableOpacity style={s.small} disabled={!member} onPress={() => mutate(() => setSuitAssignment(member!.uid, x.key, false))}><Text style={s.buttonText}>REMOVE</Text></TouchableOpacity></View></View>; })}
    <Text style={s.section}>HOLDERS · {holders.length}</Text>{holders.map(h => <View key={h.uid} style={s.holder}><Text style={s.result}>{h.jokerId} — {h.pips.join(', ')}</Text>{h.pips.map(p => <TouchableOpacity key={p} style={s.small} onPress={() => mutate(() => stampSuitCompletion(h.uid, p))}><Text style={s.buttonText}>STAMP {p}</Text></TouchableOpacity>)}</View>)}</View>;
}
const s = StyleSheet.create({ root:{flex:1,backgroundColor:'#050403'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#050403'},nav:{backgroundColor:'#000',flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingBottom:10},back:{color:GOLD,fontSize:34,lineHeight:30},navTitle:{flex:1,textAlign:'center',color:CREAM,fontFamily:'Cinzel_700Bold',letterSpacing:3,fontSize:16},content:{padding:16,paddingBottom:80},copy:{color:CREAM,textAlign:'center',fontFamily:'Cinzel_400Regular',marginBottom:15},note:{color:'#ff9b75',textAlign:'center',marginBottom:12},cards:{flexDirection:'row',flexWrap:'wrap',gap:10,justifyContent:'center'},card:{width:'47%',minHeight:160,backgroundColor:'#060606',borderColor:'#56431b',borderWidth:1,borderRadius:7,alignItems:'center',justifyContent:'center',padding:10},held:{borderColor:GOLD,backgroundColor:'#100d06'},pip:{fontSize:42,color:GOLD},suitName:{color:CREAM,fontFamily:'Cinzel_700Bold',fontSize:13},meta:{color:'#aa9c85',fontSize:11,marginTop:7},play:{color:GOLD,fontSize:10,letterSpacing:2,marginTop:5},stamped:{color:'#7fb07f',fontSize:10,marginTop:4},section:{color:GOLD,fontFamily:'Cinzel_700Bold',letterSpacing:2,fontSize:12,marginTop:28,marginBottom:10},lookup:{flexDirection:'row',gap:8},input:{color:CREAM,borderWidth:1,borderColor:'#70551d',backgroundColor:'#0a0907',borderRadius:6,padding:10,flex:1},button:{borderWidth:1,borderColor:GOLD,paddingHorizontal:12,justifyContent:'center'},buttonText:{color:GOLD,fontSize:9,fontFamily:'Cinzel_700Bold'},result:{color:CREAM,marginTop:10},footer:{color:'#aa9c85',fontSize:12,lineHeight:18,marginTop:24,fontStyle:'italic'},adminPip:{color:CREAM,marginBottom:6},small:{borderWidth:1,borderColor:'#70551d',padding:7},holder:{paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#302816',flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:6},editor:{borderWidth:1,borderColor:'#302816',padding:9,marginBottom:8},dest:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:6} });